spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: fcy123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
