spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: fcy
    password: 123
    # 确认消息成功发送，成功会进行回调
    publisher-confirms: true
    # 对于没有发送成功的消息，会进行回调
    publisher-returns: true
    # 这个按照自己需求配置，默认不配置是 /
    virtual-host: /fcy

# 自定义消息队列名称
rabbitmq:
  queue:
    msg: spring-boot-queue-msg
    user: spring-boot-queue-user
    routingKey: rabbit.#
    topic: my-topic
