spring:
  cache:
    type: redis
    redis:
      # 是否允许redis缓存null值
      cache-null-values: true
      # 缓存超时时间戳，配置为0则不设置超时时间
      time-to-live: 0
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 1000
    # 配置连接池属性
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000
  datasource:
    url: jdbc:mysql://localhost:3306/study?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: fcy123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


