spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: fcy123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
#    initialize-schema: always
    job:
      # 禁止Spring Batch自动执行。默认情况下，当项目启动时就会执行配置好的批处理操作，如果是false，则需要用户手动触发执行
      enabled:
debug: true